---
abstract: 'Perl extension converting between Daud encoding and other styles'
author:
  - 'Michael Houghton, C<< <herveus at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Daud
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
